serial:
  baudrate: 115200
  ports_prefix: /dev/ttyACM

uids:
  C1000001: T-01
  C2000001: R-01
  CFFFFFFF: broadcast

watchdog_interval: 9 # Seconds

api_server:
  protocol: https
  host: beta.handddle.com
  licence_key: HANDDDLE

influxdb:
  protocol: https
  host: data.beta.handddle.com
  org: handddle
  token: 5GEStuLlJu6-GqL3nDDxknaVTHOiB24xa2GlS5-7yswL2EtPOmhlBmldLLRohNBIoeM9FQ8-rHCKrxj3iZONgQ==
  bucket: farm_data

scanner:
  serial_base: 0x18502
  baudrate: 9600

debug: false

demo: false
