serial:
  baudrate: 9600
  ports_prefix: /dev/ttyACM

uids:
  C0C0C0C0: T-01
  C0C0C0C1: T-02
  CFFFFFFF: broadcast

watchdog_interval: 9 # Seconds

api_server:
  protocol: https
  host: beta.handddle.com
  licence_key: HANDDDLE

scanner:
  serial_base: 0x18502
  baudrate: 9600

debug: true
