serial:
  baudrate: 9600
  ports_prefix: ttyACM

uids:
  c0c0c0c0: T-01
  c0c0c0c1: T-02

root_dir: D:\Documents\PycharmProjects\handddle_farm
received_data_dir: json_files/received_data
commands_dir: json_files/commands

debug: false
