serial:
  baudrate: 9600
  ports_prefix: /dev/ttyACM

uids:
  C0C0C0C0: T-01
  CFFFFFFF: broadcast

watchdog_interval: 9 # Seconds

api_server:
  protocol: https
  host: beta.handddle.com
  licence_key: HANDDDLE

debug: false
