serial:
  baudrate: 115200
  ports_prefix: /dev/ttyACM

uids:
  #C0C0C0C0: TEST
  C1000001: T-01
  C2000001: R-01
  CFFFFFFF: broadcast

watchdog_interval: 9 # Seconds

api_server:
  protocol: https
  host: beta.handddle.com
  licence_key: HANDDDLE

influxdb:
  protocol: https
  host: #data.influxtests.handddle.com
  org: #handddle
  token: #4yiGMxQOYP21UcJPJuyq6ptRvdEE0PJyK5Greo5pgkZWCsdJfFw8NaxJf6-viD9Mjwh49JOzJcibCuU9Tl5v3Q==
  bucket: #farm_data

scanner:
  serial_base: 0x18502
  baudrate: 9600

debug: false

demo: false
